services:
  fpm:
    restart: always
    build:
      context: .
      dockerfile: xdebug/Dockerfile
      target: composer-install
    env_file: .env

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - fpm
    ports:
      - "9001:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
